/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2e004e",
        "on-primary-fixed": "#1c1b1b",
        "primary": "#000000",
        "surface-bright": "#faf9f4",
        "secondary-fixed": "#c3f400",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#444748",
        "secondary-container": "#c1f100",
        "secondary-fixed-dim": "#abd600",
        "primary-container": "#1c1b1b",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f2f1ec",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#3c4d00",
        "surface-variant": "#e3e3de",
        "error-container": "#ffdad6",
        "background": "#faf9f4",
        "on-secondary-fixed": "#161e00",
        "surface-dim": "#dbdad5",
        "tertiary-fixed": "#f2daff",
        "surface-container-low": "#f5f4ef",
        "surface-container": "#efeee9",
        "outline-variant": "#c4c7c7",
        "outline": "#747878",
        "inverse-surface": "#30312e",
        "on-primary": "#ffffff",
        "secondary": "#506600",
        "inverse-primary": "#c8c6c5",
        "tertiary-container": "#2e004e",
        "surface-container-highest": "#e3e3de",
        "on-primary-fixed-variant": "#474746",
        "on-primary-container": "#858383",
        "primary-fixed-dim": "#c8c6c5",
        "on-surface": "#1b1c19",
        "tertiary": "#000000",
        "primary-fixed": "#e5e2e1",
        "surface-tint": "#5f5e5e",
        "tertiary-fixed-dim": "#e1b6ff",
        "on-secondary-container": "#546b00",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#5d347c",
        "surface-container-high": "#e9e8e3",
        "surface": "#faf9f4",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-background": "#1b1c19",
        "on-tertiary-container": "#9d72bf"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "160px",
        "margin-desktop": "80px",
        "margin-mobile": "24px",
        "gutter": "32px",
        "container-max": "1440px"
      },
      fontFamily: {
        sans: ["var(--font-hanken-grotesk)", "sans-serif"],
        display: ["var(--font-plus-jakarta-sans)", "sans-serif"],
      }
    },
  },
  plugins: [],
}
